/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerateLinksRouteImport } from './routes/generate-links'
import { Route as IndexRouteImport } from './routes/index'

const GenerateLinksRoute = GenerateLinksRouteImport.update({
  id: '/generate-links',
  path: '/generate-links',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate-links': typeof GenerateLinksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate-links': typeof GenerateLinksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate-links': typeof GenerateLinksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generate-links'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generate-links'
  id: '__root__' | '/' | '/generate-links'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateLinksRoute: typeof GenerateLinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generate-links': {
      id: '/generate-links'
      path: '/generate-links'
      fullPath: '/generate-links'
      preLoaderRoute: typeof GenerateLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateLinksRoute: GenerateLinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
